version: '3'

services:
  app:
    stdin_open: true
    build:
      context: .
      dockerfile: "./Dockerfile"
    tty: true
    ports:
      - 6900:6900
    expose:
      - 6900
    volumes:
      - "./app:/app"
      - "~/.bash_history:/root/.bash_history"
      - "~/.bash_aliases:/root/.bash_aliases"
      - "~/.bashrc:/root/.bashrc"
